apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
  - seed-job.yaml
images:
  - name: ghcr.io/matchaonmuffins/clawswarm/frontend
    newTag: latest
    newName: ghcr.io/matchaonmuffins/clawswarm/frontend
    digest: sha256:93d8a01dd8a3be2e6b3348d6de09a8ca54d7f52df0905b57abb3f872bbcec977
  - name: ghcr.io/matchaonmuffins/clawswarm/backend
    newTag: latest
    newName: ghcr.io/matchaonmuffins/clawswarm/backend
    digest: sha256:817b0eb45aa0fa5d7a8f0fc1a2ff7383e1f58ae1d68715854d837565307e0a78
