apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/matchaonmuffins/clawswarm/frontend
    newTag: latest
    newName: ghcr.io/matchaonmuffins/clawswarm/frontend
    digest: sha256:a9bd2b364a9dcdf9ad8ef34cefa7519fb636889da4c40847854a1ad63932f4d8
  - name: ghcr.io/matchaonmuffins/clawswarm/backend
    newTag: latest
    newName: ghcr.io/matchaonmuffins/clawswarm/backend
    digest: sha256:f0f3a5bbece3492078b8b8efb1af8e67e7c2bc82a8aca5877ed70467940ed2d6
